### ISSUE TITLE
Public API surface

### ISSUE THREAD

**Issue by flashbackzoo** [mediasuitenz/mappy#30]
I'm currently using Mappy in a SilverStripe application and need access to the map and Leaflet objects, to make customisations to the map, without putting project specific code into the library's codebase.

My current workaround is adding a property to config and checking for it in `main.js` like this...

```javascript
if (config.map.exposeMapObject === true) {
  window.MAPPY = window.MAPPY || {};

  window.MAPPY.map = map;
  window.MAPPY.leaflet = require('../vendor/leaflet.js');
}
```

This works for my use case at the moment, but isn't great it terms of extendability. What are your thoughts on exposing Mappy data to the rest of an application, maybe via a module?

**Comment by digitalsadhu** [comment]
Changes have been merged in #39 #40
