### ISSUE TITLE
Funky layer interaction behaviour

### ISSUE THREAD

**Issue by digitalsadhu** [mediasuitenz/mappy#65]
Eg. Sometimes on a map with 2 layers 'layer 1' and 'layer 2' when you turn layer one off and then on, layer 2 is turned off.

Generally the issues seem to be around:
- turning layers on and off via key
- layer refresh when dataservice data updates

**Comment by markstuart** [comment]
I haven't been able to replicate this. Any more info you can give here? Maybe paste in your config?

**Comment by digitalsadhu** [comment]
Ok so not a real bug, was 1 layer obscuring the other.
