### ISSUE TITLE
Only displaying first geometry item in first collection

### ISSUE THREAD

**Issue by JonathanPrince** [mediasuitenz/mappy#85]
The endpoint `http://api.tmpforchch.co.nz/v3/tmps?key=9UdrU5ha&format=geojson` returns 20 geometry collections, of which only the first item(polygon) of the first collection is being displayed when i use the following config file. 

```js
var config = {
  map: {
    domElementId: 'map',
    tileLayers: {
      baseTiles: {
        url: '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        attribution: '',
        maxZoom: 18,
        zIndex: 10
      }
    },
    bounds: [
      [-43.577988,172.515934],
      [-43.461397,172.749529]
    ]
  },
  layers: [
    {
      name: 'layer1',
      type: 'geojson',
      dataSource: 'geojson-traffic'
    }
  ],
  dataSources: [
    {
      name: 'geojson-traffic',
      request: {
        url: 'http://api.tmpforchch.co.nz/v3/tmps?key=9UdrU5ha&format=geojson'
      },
      type: 'singlePoll'
    }
  ]
};

var map = Mappy.create(config);
```

**Comment by JonathanPrince** [comment]
Upon adding the following icon style to the layer object the other items were then displayed:
```js
styles: {
        icon: {
          general: {
            iconUrl: '/icons/icon.png'
          }
        }
      }
```

**Comment by digitalsadhu** [comment]
I think we need to make sure that there's a default presentation of geojson data 
- default markers
- default styles

**Comment by JonathanPrince** [comment]
I could take care of this, any preferences regarding a default style? 

A default icon for markers/pointers should be enough to solve this bug, are there any other styles that you'd like to see?

**Comment by digitalsadhu** [comment]
Awesome! 


Yea I think just default leaflet style. In leaflet I think omitting styles should get you this.
