### ISSUE TITLE
Add interface to stop / start polling

### ISSUE THREAD

**Issue by flashbackzoo** [mediasuitenz/mappy#91]
Our application is using a longPoll data service which we need to stop / start based on UI interaction. I see the DataService class has 'start' and 'stop' methods, which look useful here. What are your thoughts on exposing an interface to stop / start longPoll data services?

**Comment by digitalsadhu** [comment]
Yup, I don't wee why not.

We can take a look at that.

**Comment by markstuart** [comment]
Apologies for the delay @flashbackzoo, just starting work on this now

**Comment by markstuart** [comment]
See latest changes @flashbackzoo, map API methods added for start/stop of data services in v0.5.0 :smile:

**Comment by flashbackzoo** [comment]
Awesome, thanks guys!
